### ISSUE TITLE
Problema al instalar Protractor para la realización de test en la IU

### ISSUE THREAD

**Issue by aamjX** [EGCPractica/agora-gui-admin#1]
Cuanto intento instalar Protractor e introduzco el siguiente comando:

`npm install -g protractor`

Ocurre el siguiente error, del cual adjunto captura:

![photo_2017-01-06_17-28-21](https://cloud.githubusercontent.com/assets/22937991/21726646/ef7fe1a0-d43d-11e6-8965-be4cca4b74cb.jpg)

El error es provocado por una versión no adecuada de node, sin embargo, en mi sistema la versión actual de node es válida (0.10.31). Según la documentación oficial es suficiente con tener una versión superior a la 0.10. Aun así he actualizado nodejs a su última versión LTS, pero sigue el mismo error. 

¿Alguna ocurrencia de por qué pasa esto?

Saludos

**Comment by davarresc** [comment]
Para resolver ese error actualiza a la última versión estable de node. Con los siguientes comandos actualizas a la última versión estable y se se soluciona el problema.
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by aamjX** [comment]
Perfecto, me ha funcionado perfectamente. ¡Gracias!
